export enum CompanyEntityTypeEnum {
    REPORTING_FINANCIAL_INSTITUTION = 'REPORTING_FINANCIAL_INSTITUTION',
    NON_REPORTING_FINANCIAL_INSTITUTION = 'NON_REPORTING_FINANCIAL_INSTITUTION',
    ACTIVE_NON_FINANCIAL_ENTITY_GOVERNMENTAL_OR_INTERNATIONAL = 'ACTIVE_NON_FINANCIAL_ENTITY_GOVERNMENTAL_OR_INTERNATIONAL',
    ACTIVE_NON_FINANCIAL_ENTITY_OTHER = 'ACTIVE_NON_FINANCIAL_ENTITY_OTHER',
    PASSIVE_NON_FINANCIAL_ENTITY = 'PASSIVE_NON_FINANCIAL_ENTITY'
}
