export enum ErrorsEnum {
    CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',
    FIELD_ALREADY_USED = 'FIELD_ALREADY_USED',
    FIELD_NOT_EDITABLE = 'FIELD_NOT_EDITABLE',
    FIELD_REQUIRED = 'FIELD_REQUIRED'
}
