export enum ErrorsEnum {
    FIELD_ALREADY_USED = 'FIELD_ALREADY_USED',
    FIELD_NOT_EDITABLE = 'FIELD_NOT_EDITABLE',
    FIELD_REQUIRED = 'FIELD_REQUIRED',
    USER_ROLE_INVALID = 'USER_ROLE_INVALID',
    REQUEST_CONTENT_EROR = 'REQUEST_CONTENT_EROR',
    USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN'
}
