export enum HubspotRegistrationPipelineEnum {
    PERSONAL_INFO = 'PERSONAL_INFO',
    USER_CREATED = 'USER_CREATED',
    WAITING_VALID_PAYIN = 'WAITING_VALID_PAYIN',
    WAITING_TREEZOR_REVIEW = 'WAITING_TREEZOR_REVIEW',
    WAITING_BASE_SCORE = 'WAITING_BASE_SCORE',
    VALIDATION_FINISHED = 'VALIDATION_FINISHED'
}
