export enum KycHistoryOperationTypeEnum {
    CLIENT_CREATION = 'CLIENT_CREATION',
    TREEZOR_KYC_LIVENESS_CREATION = 'TREEZOR_KYC_LIVENESS_CREATION',
    TREEZOR_KYC_LIVENESS_FAILURE = 'TREEZOR_KYC_LIVENESS_FAILURE',
    TREEZOR_KYC_LIVENESS_UPDATE = 'TREEZOR_KYC_LIVENESS_UPDATE',
    TREEZOR_KYC_LIVENESS_DEMAND = 'TREEZOR_KYC_LIVENESS_DEMAND',
    TREEZOR_KYC_UPDATE = 'TREEZOR_KYC_UPDATE',
    TREEZOR_KYC_VALIDATION = 'TREEZOR_KYC_VALIDATION',
    FREEZE_ACCOUNT = 'FREEZE_ACCOUNT',
    UNFREEZE_ACCOUNT = 'UNFREEZE_ACCOUNT',
    BASE_SCORE_DEFINED = 'BASE_SCORE_DEFINED',
    CREATE_TREEZOR_KYC_DOCUMENT = 'CREATE_TREEZOR_KYC_DOCUMENT',
    UPDATE_TREEZOR_KYC_DOCUMENT = 'UPDATE_TREEZOR_KYC_DOCUMENT'
}
