export enum KycStatusEnum {
    NONE = 'NONE',
    WAITING_LIVENESS_RESULTS = 'WAITING_LIVENESS',
    ENDING_LIVENESS = 'ENDING_LIVENESS',
    WAITING_TREEZOR_RESULTS = 'WAITING_TREEZOR_RESULTS',
    WORLD_CHECK_SCREENING_FAILED = 'WORLD_CHECK_SCREENING_FAILED',
    WORLD_CHECK_REVIEW = 'WORLD_CHECK_REVIEW',
    WAITING_RISK_SCORE = 'WAITING_RISK_SCORE',
    WAITING_DOCS = 'WAITING_DOCS',
    VALIDATED = 'VALIDATED',
    REFUSED = 'REFUSED',
    SUSPICIOUS_TRANSFER = 'SUSPICIOUS_TRANSFER'
}
