export enum KycHistoryOperationTypeEnum {
    CLIENT_CREATION = 'CLIENT_CREATION',
    TREEZOR_KYC_LIVENESS_DEMAND = 'TREEZOR_KYC_LIVENESS_DEMAND',
    FREEZE_ACCOUNT = 'FREEZE_ACCOUNT',
    UNFREEZE_ACCOUNT = 'UNFREEZE_ACCOUNT',
    BASE_SCORE_DEFINED = 'BASE_SCORE_DEFINED'
}
