export enum KycStatusEnum {
    NONE = 'NONE',
    WAITING_TREEZOR_RESULTS = 'WAITING_TREEZOR_RESULTS',
    WAITING_RISK_SCORE = 'WAITING_RISK_SCORE',
    WAITING_DOCS = 'WAITING_DOCS',
    VALIDATED = 'VALIDATED',
    REFUSED = 'REFUSED'
}
