export enum SocioProfessionalCategoryEnum {
    FARMER = 'FARMER',
    TRADESMAN_ENTREPRENEUR = 'TRADESMAN_ENTREPRENEUR',
    EXECUTIVE_INTELLECTUAL = 'EXECUTIVE_INTELLECTUAL',
    INTERMEDIATE = 'INTERMEDIATE',
    EMPLOYEE = 'EMPLOYEE',
    WORKER = 'WORKER'
}
