export enum TransactionOperationTypeEnum {
    CREATE_DEPOSIT = 'CREATE_DEPOSIT',
    RECEIVE_TREEZOR_TRANSFER_CREATION_WEBHOOK = 'RECEIVE_TREEZOR_TRANSFER_CREATION_WEBHOOK',
    RECEIVE_TREEZOR_TRANSFER_UPDATE_WEBHOOK = 'RECEIVE_TREEZOR_TRANSFER_UPDATE_WEBHOOK'
}
