export enum TreezorApiTransferStatusEnum {
    STRAPI_CREATED = 'STRAPI_CREATED',
    STRAPI_REQUEST_FAILED = 'STRAPI_REQUEST_FAILED',
    STRAPI_AWATING_WEBHOOK = 'STRAPI_AWAITING_WEBHOOK',
    VALIDATED = 'VALIDATED',
    CANCELLED = 'CANCELLED',
    PENDING = 'PENDING'
}
