export enum TreezorApiTransferStatusEnum {
    CREATED = 'CREATED',
    REQUEST_FAILED = 'REQUEST_FAILED',
    AWATING_WEBHOOK = 'AWAITING_WEBHOOK',
    VALIDATED = 'VALIDATED',
    CANCELLED = 'CANCELLED',
    PENDING = 'PENDING'
}
