export enum WorldCheckInfoStatusEnum {
    NO_MATCH_FOUND = 'NO_MATCH_FOUND',
    MATCH_FOUND_AWAITING_REVIEW = 'MATCH_FOUND_AWAITING_REVIEW',
    MATCH_FOUND_BUT_ACCEPTED = 'MATCH_FOUND_BUT_ACCEPTED',
    MATCH_FOUND_AND_REJECTED = 'MATCH_FOUND_AND_REJECTED'
}
