export interface TreezorPayinModel {
    creditorIban: string,
    debtorIban: string,
    debtorBic: string,
    debitorName: string,
    virtualIbanId: string,
    virtualIbanReference: string,
    transactionEndToEndId: string,
    transactionId: string,
    settlementAmount: number,
    settlementDate: string,
}

export interface StrapiTreezorPayinFormModel {
    payinId?: string
    payinTag?: string,
    payinStatus?: string, 
    paymentMethodId?: number,
    messageToUser?: string,
    subtotalItems?: string,
    subtotalServices?: string,
    subtotalTax?: string,
    amount: number,
    currency?: string,
    createdDate: string | null,
    walletEventName?: string,
    walletAlias?: string,
    codeStatus?: number,
    informationStatus?: string,
    refundAmount?: number,
    ibanTxEndToEndId: string,
    ibanTxId: string,
    forwardUrl?: string,
    paymentAcceptedUrl?: string,
    paymentRefusedUrl?: string,
    paymentWaitingUrl?: string,
    paymentExceptionUrl?: string,
    paymentCanceledUrl?: string,
    payinDate?: string | null,
    mandateId?: number,
    virtualIbanId: string,
    virtualIbanReference: string,
    additionalData?: string,
    ibanId?: string,
    treezorUser: number,
    beneficiary: number

}