export enum TreezorWebhookPayloadTypeEnum {
    'BALANCE' = 'balance',
    'BENEFICIARY' = 'beneficiary',
    'SEPASCTR' = 'sepaSctr',
    'RECALLR' = 'recallr',
    'CARD' = 'card',
    'CARDDIGITALIZATION' = 'cardDigitalization',
    'CARDTRANSACTION' = 'cardtransaction',
    'CARD_ACQUIRING' = 'card.acquiring',
    'COUNTRYGROUP' = 'countryGroup',
    'DOCUMENT' = 'document',
    'MANDATE' = 'mandate',
    'MCCGROUP' = 'mccGroup',
    'MERCHANTIDGROUP' = 'merchantIdGroup',
    'SEPASDDE' = 'sepaSdde',
    'SEPASDDR' = 'sepaSddr',
    'PAYIN' = 'payin',
    'PAYINREFUND' = 'payinrefund',
    'PAYOUT' = 'payout',
    'TRANSACTION' = 'transaction',
    'TRANSFER' = 'transfer',
    'USER' = 'user',
    'KYCLIVENESS' = 'kycliveness',
    'WALLET' = 'wallet',
}
