export enum TreezorWebhookPayloadTypeEnum {
    'balance' = 'balance',
    'beneficiary' = 'beneficiary',
    'sepaSctr' = 'sepaSctr',
    'recallr' = 'recallr',
    'card' = 'card',
    'cardDigitalization' = 'cardDigitalization',
    'cardtransaction' = 'cardtransaction',
    'card.acquiring' = 'card.acquiring',
    'countryGroup' = 'countryGroup',
    'document' = 'document',
    'mandate' = 'mandate',
    'mccGroup' = 'mccGroup',
    'merchantIdGroup' = 'merchantIdGroup',
    'sepaSdde' = 'sepaSdde',
    'sepaSddr' = 'sepaSddr',
    'payin' = 'payin',
    'payinrefund' = 'payinrefund',
    'payout' = 'payout',
    'transaction' = 'transaction',
    'transfer' = 'transfer',
    'user' = 'user',
    'kyvliveness' = 'kyvliveness',
    'wallet' = 'wallet'
}
