export enum TreezorKycLivenessScoreEnum {
    NOT_STARTED = 'NOT_STARTED',
    MISSING_DOCUMENTS = 'MISSING_DOCUMENTS',
    INVALID_DOCUMENTS = 'INVALID_DOCUMENTS',
    READY_FOR_REVIEW = 'READY_FOR_REVIEW',
    PENDING = 'PENDING'
}
