import { TreezorCommonWalletTypeEnum } from '../enums/common-wallets/treezor-common-wallet-type.enum';

export interface CommonTreezorWalletModel {
    walletId: number,
    walletTypeId: number,
    walletStatus: string,
    codeStatus: number,
    informationStatus: string,
    walletTag: string,
    userId: number,
    userLastname: string,
    userFirstname: string,
    jointUserId: number,
    tariffId: number,
    eventName: string,
    eventAlias: string,
    eventDate: string,
    eventMessage: string,
    eventPayinStartDate: string,
    eventPayinEndDate: string,
    contractSigned: number,
    bic: string,
    iban: string,
    urlImage: string,
    currency: string,
    createdDate: string,
    modifiedDate: string,
    payinCount: number,
    payoutCount: number,
    transferCount: number,
    solde: number,
    authorizedBalance: number,
    totalRows: number,
    walletType: TreezorCommonWalletTypeEnum
}
