export enum FireblocksApiTransferPeerPathTypeEnum {
    VAULT_ACCOUNT = 'VAULT_ACCOUNT',
    EXCHANGE_ACCOUNT = 'EXCHANGE_ACCOUNT',
    INTERNAL_WALLET = 'INTERNAL_WALLET',
    EXTERNAL_WALLET = 'EXTERNAL_WALLET',
    ONE_TIME_ADDRESS = 'ONE_TIME_ADDRESS',
    NETWORK_CONNECTION = 'NETWORK_CONNECTION',
    FIAT_ACCOUNT = 'FIAT_ACCOUNT',
    COMPOUND = 'COMPOUND',
    UNKNOWN = 'UNKNOWN'
}
